version: '3'

tasks:
  server:
    cmds:
      - air

  wasm:
    cmds:
    - goreleaser release --snapshot --clean
    - cp -p ./dist/webasm_js_wasm/main.wasm ./web/html/js/
    - cp -p "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./web/html/js/wasm_exec.js

  tinygo:
    cmds:
    - mkdir -p ./dist/tinygo
    - GOOS=js GOARCH=wasm tinygo build -o ./dist/tinygo/main.wasm ./cmd/wasm/main.go
    - cp -p ./dist/tinygo/main.wasm ./web/html/js/
    - cp -p "$(tinygo env TINYGOROOT)/targets/wasm_exec.js" ./web/html/js/wasm_exec.js

  test:
    - go test -v ./...
